#!/usr/bin/env python3
# build_a25.py — A25 v1 = A24 v1_3 HTML (bytes verified) + A25 proposals marked RED (text + SVG).
# Every insertion is keyed by an exact anchor substring of A24 v1_3; a missing anchor aborts (no silent drift).
import hashlib, re, sys, datetime

SRC = 'A24_cwf-capability-fabric-architecture-v1_3.html'
DST = 'A25_cwf-capability-fabric-architecture-v1.html'
A24_SHA = '99444e2b4e971f770c453426297385cb66998bb2ac603da4b427a741f14497d4'

raw = open(SRC, 'rb').read()
assert hashlib.sha256(raw).hexdigest() == A24_SHA, 'A24 v1_3 bytes differ from the verified source'
html = raw.decode('utf-8')
NOW = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%MZ')

def ins_after(anchor, text, count=1):
    global html
    n = html.count(anchor)
    assert n >= 1, 'anchor missing: ' + anchor[:60]
    if count == 1:
        assert n == 1, f'anchor not unique ({n}): ' + anchor[:60]
    html = html.replace(anchor, anchor + text, 1)

def ins_before(anchor, text):
    global html
    assert html.count(anchor) == 1, 'anchor not unique/missing: ' + anchor[:60]
    html = html.replace(anchor, text + anchor, 1)

def rep(old, new):
    global html
    assert html.count(old) == 1, 'replace anchor not unique/missing: ' + old[:60]
    html = html.replace(old, new, 1)

# ── 0 · title, header, CSS ────────────────────────────────────────────────────
rep('<title>A24 · CWF Capability Fabric — Backend-Agnostik, Kendi Kendine Öğrenen Anlama Katmanı · v1_3</title>',
    '<title>A25 · CWF Capability Fabric — A24 v1_3 + Yetenek Yönlendiricisi önerisi (kırmızı) · v1</title>')
ins_after('</style>', '''
<style>
/* ── A25 v1 · every A25 proposal is RED, dashed and badged "A25"; A24's own red (--rd, solid) keeps its meaning: today's defect / removed ── */
:root{--a25:#D00000;--a25-f:#FFF3F2}
.a25{color:var(--a25)}
.a25b{color:var(--a25);font-weight:700}
.a25del{color:var(--a25);text-decoration:line-through;text-decoration-thickness:2px}
.a25box{border:2px dashed var(--a25);background:var(--a25-f);border-radius:8px;padding:12px 16px;margin:12px 0;color:var(--ink)}
.a25box b.h{color:var(--a25)}
.a25badge{display:inline-block;font:700 11px ui-monospace,monospace;color:#fff;background:var(--a25);border-radius:5px;padding:1px 7px;margin-right:6px;vertical-align:middle}
tr.a25row td{border-left:4px solid var(--a25);background:var(--a25-f)}
tr.a25row td:first-child{color:var(--a25);font-weight:700}
.card.a25c{border:2px dashed var(--a25);border-left:6px solid var(--a25);background:var(--a25-f)}
.card.a25c h4{color:var(--a25)}
.sw.a25{background:var(--a25-f);border-color:var(--a25);border-style:dashed}
svg .a25s{stroke:var(--a25);stroke-width:1.6;stroke-dasharray:6 4;fill:var(--a25-f)}
svg .a25l{stroke:var(--a25);stroke-width:1.6;stroke-dasharray:6 4;fill:none}
svg .a25t{fill:var(--a25);font:600 11px "Avenir Next","Segoe UI",sans-serif}
svg .a25m{fill:var(--a25);font:10.5px ui-monospace,"SF Mono",Consolas,monospace}
svg .a25x{stroke:var(--a25);stroke-width:2.2}
</style>''')

rep("""<div class="docid">A24_cwf-capability-fabric-architecture-v1_3 · rev 1.3 · 2026-09-21 · S149 · SUPERSEDES v1_2 rev 1.2 ve v1 rev 1.0 · anchor master 7572c3bb… (iddia) · beside A23 v1_4 (LOCKED) · IR-4 Path B'yi canlıya taşır</div>""",
    f"""<div class="docid"><span class="a25badge">A25</span>A25_cwf-capability-fabric-architecture-v1 · rev 1.0 · {NOW[:10]} · S159/S160 · A24 v1_3 (rev 1.3, S149, sha256 {A24_SHA[:16]}…) BAYT BAYT KORUNDU + kırmızı A25 önerileri · anchor master b8e5b1d95b76b92b0c20383ebd7a1d0bf9c7da6f (PR 622 inişi, Vercel prod) · ÖNERİ — sahip hükmü OWNER-RULING-S160-ROUTING-V2-1 bekliyor</div>""")
rep('<h1>CWF Capability Fabric <span class="v">v1_3 · FİNAL ADAY · sahip hükümlü defter işlendi · kart kesilmedi</span></h1>',
    '<h1>CWF Capability Fabric <span class="v">A24 v1_3 (siyah, aynen) + <span class="a25b">A25 v1 önerisi (KIRMIZI)</span> · kart kesilmedi · kod dokunulmadı</span></h1>')
ins_after("""<span class="status">STATUS: TARGET-STATE DESIGN · OWNER-RULING-S149-LEDGER-1 işlendi · Q3/Q4 üretim tanıklığı işlendi · kaynaklar §Δ ve §10'da adıyla</span>""",
    '''
<div class="a25box"><b class="h">A25 NASIL OKUNUR.</b> Siyah metin ve diyagramlar A24 v1_3'ün KENDİSİDİR (bayt bayt; hiçbir A24 cümlesi silinmedi, kısaltılmadı). <span class="a25b">Kırmızı, kesikli çerçeveli ve "A25" rozetli her şey ÖNERİDİR</span>: ya A24'ün üstüne bir EKLEME, ya da A24'ten bilinçli bir SAPMA — sapmalar §Δ25 tablosunda "Sahibin hükmü" sütunuyla tek tek listelenir; sahip hükmedene kadar A24 v1_3 yürürlüktedir. <span class="a25del">Kırmızı üstü çizili</span> = A25'in kaldırılmasını önerdiği A24/bugün ögesi. A24'ün kendi kırmızısı (düz çerçeve, "bugünkü defekt · kaldırılan") anlamını korur; A25 kırmızısı kesiklidir ve rozetlidir. Tasarım kaynakları adıyla (S112-YASA-1): <b>OWNER-DESIGN-S159-1</b> (sahip: 6×13 matris ve koda gömülü sözlük yapısal çöp; kendi kendine öğrenen/konfigüre olan/iyileşen, backend-agnostik yönlendirici) · <b>EXT-DESIGN-S159-ASTRA-1</b> (dış inceleme, sahibin toplamasıyla; ölçümü CWF-ASTRA-REVIEW-EVALUATION-S159-1) · <b>SCOUT S159-1 / S159-2</b> (iki hasım hükmü, D1–D17) · Architect kör noktaları A-REC-S159-1/2/3 (§10'a kırmızıyla eklendi).</div>''')

# ── §Δ25 · the change register, before §Δ ─────────────────────────────────────
delta25 = '''
<section id="sd25">
<h2><span class="sn a25">§Δ25</span><span class="a25">A24 v1_3 → A25 v1 · DEĞİŞİKLİK KAYDI — her satır bir öneri; "Sahibin hükmü" sütunu boş</span></h2>
<div class="a25box"><b class="h">Sınıflandırma.</b> <b>EK</b> = A24'ün hiçbir kuralını daraltmayan ekleme (A24 kuralı aynen kalır). <b>SAPMA</b> = A24'ün bir kuralından bilinçli ayrılma; ancak sahip hükmüyle yürürlüğe girer. <b>ÖNE ALMA</b> = A24'ün zaten karar verdiği bir kaldırmanın erken kesilmesi. Bugünkü kod (master b8e5b1d9…) ile A24 arasındaki farklar "bugün" sütununda ölçümle yazılır; A24 bir hedef-durum tasarımıdır, bugünkü kod A24 değildir.</div>
<table>
<tr><th style="width:4%">#</th><th style="width:12%">Konu</th><th style="width:22%">A24 v1_3 diyor</th><th style="width:14%">Bugün (ölçüldü, S159)</th><th>A25 öneriyor (KIRMIZI)</th><th style="width:7%">Sınıf</th><th style="width:11%">Kaynak</th><th style="width:9%">Sahibin hükmü</th></tr>
<tr class="a25row"><td>1</td><td>MATRIX ve kapalı enum'lar</td><td>§7: st07 = hibrit retrieval → conformal set; §10: "kelime listesi yönlendiricisi kaldırıldı; keyword yalnız merdiven tabanı". MATRIX'i anmaz (A24 hedef tasarımdır).</td><td>deriveCategories.ts:63–92 MATRIX HIGH'da router seçiminin YERİNE geçer; irFrame.ts:54–62 6 eylem × 13 nesne (COMPANY yok); coreSchemas.ts:136 alias katmanı z.enum([factory,line,zone,equipment]); toolArgPolicy.ts:284–286 katman başına satır; ALWAYS_INCLUDE :1203; assemble.ts:55 'superset'.</td><td><b>MATRIX yerine-geçme kuralı yönlendirme yolundan SİLİNİR</b> (P4/E5'te; o güne kadar <code>router.matrixReplace=0</code> ile hükümsüz). Çerçeve GÖZLEM olarak kalır ve K24 <code>frame{}</code> alanını besler. <b>IR_OBJECTS kapalı enum → yönetişimli sözlük (veri)</b>, ilk eklenen satır COMPANY; <code>backend_entity_layers.frame_object</code> bu sözlüğe bakar. Alias katman enum'u <code>backend_entity_layers</code>'tan türetilir; arg-policy satır zorunluluğu katman-agnostik olur. planner.ts'in IrAction anahtarları çerçeve sözlüğünü OKUMAYA devam eder (K26/§13.1 organ korunur).</td><td>SAPMA (bugüne göre) / EK (A24'e göre)</td><td>OWNER-DESIGN-S159-1 · scout D8, (x)</td><td>R6(a)</td></tr>
<tr class="a25row"><td>2</td><td>Yönetişimli veri üç sınıf; yükümlülük türü</td><td>P4: "keyword as ladder floor"; K10 yetki katmanı bağlayıcı; K1 kilitli küçük set.</td><td>tool_category 13 satır / 154 anahtar kelime (kod tabanı) / 113 araç yuvası; anahtar kelime yalnız fallback+frame+sticky'de; semantik yolda mevcut mesaj için hiç bakılmıyor (T2).</td><td>(i) <b>YETKİ KISITLARI</b> = K10 aynen. (ii) <b>AÇIK YÖNLENDİRME YÜKÜMLÜLÜĞÜ</b> = YENİ yönetişimli tür <code>routing_obligation</code>, birimi <b>(koşul, ARAÇ)</b> — asla kategori; süzgeçli yolda sunulan kümeye girer ve K1 bütçesine ÖNCE sayılır; Anthropic'te PLAN kısıtı (satır 4). Yalnız yükümlülükler bütçeyi aşarsa tur <code>OBLIGATION-OVERFLOW</code> damgası alır, sahip Kurallar sekmesinde görür. (iii) <b>ALAKA İPUÇLARI</b> = mevcut anahtar kelimeler, metrik ipuçları, tahmini katman, sticky: sıralama KANITI ve A24 P4'ün merdiven tabanı (bugünkü fallback davranışı AYNEN). <b>Göç varsayılanı: HİNT</b>; yükümlülük yalnız sahibin arayüzden yayınladığı satırlar (ilk dördü: dört tanığın anahtarları); LEARNED eşlemeler (tool_cache) ASLA yükümlülüğe göçmez. Ölçüm: "hepsi yükümlülük" olsaydı 185 turda yükümlü araç p50 13 / p90 46 / max 56, 'tüketim' tek başına 42 araç → taşma normal durum olurdu.</td><td>EK</td><td>EXT-DESIGN-S159-ASTRA-1 A1 · scout D4/D6</td><td>R6(b)</td></tr>
<tr class="a25row"><td>3</td><td>K1 bütçesi ilan</td><td>K1: "per-turn max K tools and max schema tokens DECLARED"; K18 şema token tavanı.</td><td><code>router.maxTools</code>, <code>router.maxSchemaTokens</code>, <code>router.maxFanout</code> ne DB'de ne kodda (tek isabet derivedPack.ts:108 MAX_TOOLS=40, görüntü tavanı); maxCategories=4; bugün sunulan p50 26, max 171.</td><td>Üç yönetişimli parametre <b>E2'de yaratılır</b> (kod) ve E1 tabanından ilk değerleri ilan edilir; taşma istatistiği bütçe var olmadan yazılmaz.</td><td>EK</td><td>scout D5 · Astra A8</td><td>—</td></tr>
<tr class="a25row"><td>4</td><td>K1 Anthropic'te</td><td>K1 kilitli küçük set — sağlayıcı ayrımı yok; K20 "Anthropic PTC isteğe bağlı hızlı yol".</td><td>stageTools.ts:551: Anthropic'te kapsam içi TÜM araçlar sunulur ("cache mode, stable prefix"); çerçeve YOK (resolveTurnFrame.ts:172 absent ROUTING_BYPASS), stage 03 KARANLIK (stageClarify.ts:2764), planlayıcı bloğu yok; son 185 turun 185'i Anthropic dışı.</td><td><b>K1 her sağlayıcıya uygulanır</b> (A24 zaten böyle der); Anthropic'in süzgeçli yola geçişi <b>E1'in FATURA maliyeti ölçümüyle</b> kapılanır (Toollery App. B.2: görünür token azalması fatura tasarrufu değildir; önbellek durumu kaydedilir). Geçişe kadar Anthropic'te yükümlülük <b>PLAN yükümlülüğüdür</b>: st07p planı yükümlü aracı çağırır ya da çağırmama nedenini yazar; iz <code>obligation_honoured</code> ile ölçer. Yükümlü araçların şema/özetleri önbellek ön-ekinde SABİT kalır (tur başına yeniden sıralama yok). Tam-katalog yolu lab bayrağı (routingBypass) olarak kalır.</td><td>SAPMA (bugüne göre) · A24 K1'e DÖNÜŞ</td><td>Astra A2 · scout D7 · Toollery B.2</td><td>R6(f)</td></tr>
<tr class="a25row"><td>5</td><td>Araç kimliği</td><td>K6: <code>backend.tool</code> ad alanı + hash pin.</td><td>toolRetrieval.ts:335 birleşim <code>seen.has(c.tool)</code> (çıplak ad); stageTools.ts:1281 claimToolName ikinci sahibi reddeder; T2'de honestbench ve mount-probe aynı indeksleri [4,5,6,7] taşıyor.</td><td>Kimlik = <b>server_id + backend_id + tool</b> her yerde (getirme birleşimi, kayıt, iz, kartlar); model-yüzlü ad türetilir ve çakışmasızdır; T2 çakışması E2'nin ilk kırmızı testi.</td><td>EK (K6 uzantısı)</td><td>Astra A3</td><td>—</td></tr>
<tr class="a25row"><td>6</td><td>Yayın kapısı kapsamı</td><td>§6/§8: her öneri kapıdan (K23 → sınav → K25 aralığı) geçer.</td><td>governance.ts:427–434: decideGoldenPublish YALNIZ prompt.segment; tool_category / ipucu / politika satırları sınavsız yayınlanır.</td><td>decideGoldenPublish <b>tool_category · routing_obligation · ranking_policy · tool_profile · kart demeti</b> için de kapı olur — KABLOLAMA (12.6), ikinci kapı değil.</td><td>EK</td><td>Astra A4</td><td>—</td></tr>
<tr class="a25row"><td>7</td><td>Keşif zinciri</td><td>K1: tool_search ertelenmişleri açar; §12 açık soru 2: CWF'nin kendi indeksi varsayılan, Anthropic native isteğe bağlı; K10 tools/call'da yeniden kontrol.</td><td>search_tools yalnız gateway backend'inde (Superset); platform-geneli keşif aracı yok.</td><td>K1'in tool_search'ü <b><code>cwf_find_capability</code></b> adıyla, sağlayıcı-agnostik: ara → yetkili kart (K21 demeti) → güncel şema → kayıt (satır 5 kimliğiyle) → BİR SONRAKİ model adımında kullanılabilir; K10'un tools/call yeniden kontrolü, "kapsam eşleşmesi çağrı yetkisi vermez" ve "kapsam değişince indeks/önbellek/LEARNED geçersiz" tur-içi kayda BAĞLANIR. Her kullanım INITIAL-NEED-MISS (kaçırma defteri; register kalem 9) ya da NEXT-STEP-DISCOVERY olarak sınıflanır; yalnız ilki §6'nın taban-küme önerisine girer.</td><td>EK</td><td>Astra A5 · scout D12</td><td>—</td></tr>
<tr class="a25row"><td>8</td><td>İz: yönlendirme olayı</td><td>K24: cwf.trace.v1 dondurulmuş (§7b); tool_experience bir SAYAÇ (A-REC-S149-6).</td><td>cwf.trace.v1 KODDA YOK (tek geçtiği yer bir rapor cümlesi); tool_experience per-turn upsert (runTurn.ts:303), oku-topla-upsert yarışı (ToolExperienceRepository.ts:110–150); censusToolDoc.ts:137–153 "used successfully in practice" cümlesini model-yüzlü açıklamaya ekliyor (toolCensus.composeEnabled, taban 0, canlı UNMEASURED).</td><td><b>cwf.trace.v2 = v1 + alan haritası</b> (araç başına candidate/offered/selected/sent/reason · <code>governedKept</code> · <code>obligation_honoured</code> · catalog_version · policy_version); APPEND-ONLY; tur SONRASI etiketler (K23 sonucu, kullanıcı düzeltmesi, tekrar soru) trace_id ile anahtarlı AYRI etiket kaydında; <code>result_class</code> sözlüğü K24'ünki. tool_experience bu izin GÖRÜNÜMÜ olur ya da emekli edilir. composeEnabled bir FREN kalemi (satır 13).</td><td>EK (K24 sürüm artışı)</td><td>Astra A6 · scout D6/D9/D13</td><td>—</td></tr>
<tr class="a25row"><td>9</td><td>Kart yüzleri +2</td><td>§3 dokuz yüz; K28 çıktı sözleşmeleri; K29 takvim; K22 kısmi korpus UNMEASURED.</td><td>—</td><td><b>TOPLULAŞTIRMA yüzü</b> (ölçü, birim, grain, tekrar-giderme anahtarı — aynı kişi iki fabrikada; zaman semantiği "bugün aktif" ≠ "dönemde çalıştı" ≠ FTE; kapsama damgası) ve <b>KAPSAM yüzü</b> (bilgi araçları için kaynak envanterinden türetilen konu/dönem/kurum kapsamı; K22'nin pozitif yarısı). Provenance sözlüğü A24 §3'ünki (DERIVED/LEARNED/CURATED). Kart evi A24 §3 aynen: mevcut kind'lar + türetilmiş kind'lar, aynı yönetişim yolu; <span class="a25del">yeni kart demeti tabloları</span> YOK — K21 demeti mevcut kind'lar üzerinde hash + işaretçidir.</td><td>EK</td><td>Astra A7 · scout D1</td><td>—</td></tr>
<tr class="a25row"><td>10</td><td>Kanıt aşamaları ve kabul tablosu</td><td>§9 P0–P5; K19 dilimli sınav; K25 baraj önceden; K11 üç küme + E2E N=10.</td><td>—</td><td>E1–E5 P0–P5'in İÇİNE yerleşir (sırayı değiştirmez, §9'a kırmızı satırlar): E1 zemin (üç sağlayıcı fatura tabanı; K-A fikstür MCP sunucusu + ikinci görülmemiş-sözlüklü backend; K-G aleti) · E2 sözleşme (kimlik, türler, iz v2, kapı, anahtar ayrımı) · E3 gölge (KAYITLI router çıktısı üzerinde kollar; canlı semantik kol tekrar oynatılamaz → yalnız E1 offline sınavla) · E4 keşif–plan–yürütme (router çağrısının ayrılması; şirket katmanı; st07p; yürütücü v0) · E5 öğrenme + söküm. Kabul tablosuna <b>sağlayıcı</b> kırılım ekseni ve yanlış-kesin/gereksiz-vazgeçme çifti eklenir.</td><td>EK</td><td>Astra A9/A10 · scout D10/D11</td><td>R6(d)</td></tr>
<tr class="a25row"><td>11</td><td>Sıfır-kod kapsamı</td><td>K5 kart istemci tarafında; protokol sınıfı MCP/gateway.</td><td>—</td><td>"Yeni backend = sıfır kod" iddiası MCP tools/list + ilan edilmiş kimlik doğrulama + protokol sınıfı ile SINIRLIDIR; bilinmeyen auth/işlem protokolü kart kesimidir. K-G (kodda backend adı 0) GEREKLİ, yeterli değil; sınav K-A + K-A′ (iki görülmemiş sözlük).</td><td>EK</td><td>Astra A11</td><td>—</td></tr>
<tr class="a25row"><td>12</td><td>Üreticiler ayrı; niyet örnekleri</td><td>K3 profilleyici; K11 "paraphrase üreticisi ≠ profilleyici; üç ayrık küme; üretilmiş metin held-out değil".</td><td>—</td><td>Toollery tarzı <b>niyet-sorgusu üreticisi</b> (kart verisi, retrieval indeksine; kapılı) K11'e ÜÇÜNCÜ üretici olarak eklenir: niyet üreticisi ≠ sınav üreticisi ≠ profilleyici; üretilmiş hiçbir metin held-out'a girmez. Sayılar aynı koşulda: ham spec BM25 .571; genişletilmiş indekste BM25 .942 / dense .900 / RRF .945; embed+rerank ham spec .704 (aynı koşul DEĞİL); BFCL-V4'te BM25 .948 &lt; RAGAnything .980 → kazanan E3'te (K16), K15'in BM25-TR zorunluluğu içinde.</td><td>EK</td><td>Toollery · scout D11/S2</td><td>—</td></tr>
<tr class="a25row"><td>13</td><td>Frenler (P5'e kadar)</td><td>§6: LEARNED yalnız kapıdan; K12.</td><td>learnToolMapping (toolCategories.ts:950–956) ve legacy öğrenme (:1866) kapısız YAZAR ama router.learnEnabled canlıda PUBLISHED 0 (fren AÇIK); toolCensus.composeEnabled taban 0, canlı UNMEASURED.</td><td>Üç fren adıyla listelenir ve E5'e kadar AÇIK kalır: learnToolMapping · legacy :1866 · composeEnabled (model-yüzlü deneyim cümlesi). E5'te olay yoluna taşınırlar.</td><td>EK</td><td>scout S159-1/D13</td><td>—</td></tr>
<tr class="a25row"><td>14</td><td>Gölge kolları koşturulabilir</td><td>P2: retrieval gölgede; K16 ablasyon.</td><td>frameRouting kapısı (:1609) ipuçlarını, metrik tabanını, unmodeled-keep'i, derived izi VE stage 03'ü (stageClarify.ts:2771) birlikte kapatır; "keyword her yolda" anahtarı yok (:1545–1557); routeShadowLens kayıp hesaplar, kazanç hesaplamaz.</td><td>E2 KOD kalemi: <code>router.matrixReplace</code> (yerine-geçme) ve <code>router.frameEnabled</code> (gözlem/ipucu/stage 03) AYRI anahtarlar; "keyword semantik yolda" ayrı anahtar. E3 kolları digest'te KAYITLI router çıktısını (irFrame, routeProposals, offeredToolNames) sabit girdi alır: kayıtlı-sunulan · matris kapalı · keyword her yolda · BM25-TR · dense (gerçek encoder) · hibrit RRF · +reranker. Farklı bir router PROMPT'unun etkisini hiçbir kol ölçmez; onu yalnız E1 offline sınavı ölçer.</td><td>EK</td><td>scout D10, (v)</td><td>—</td></tr>
<tr class="a25row"><td>15</td><td>Şirket katmanı</td><td>K31: stage 03′ backend'in kendi listesine karşı; §7 ①→②→③ sırası: frame → aday+yuva+kapsam → plan.</td><td>backend_entity_layers: discovery_tool NOT NULL, frame_object IR enum (COMPANY yok), varlıklar "never authored" (DDL :89); FACTORY bağlaması şirket adlarını "Kayıtlı fabrikalar"a sızdırır; ilan edilmiş-boş katman → HIGH ret (computeClarification.ts:265); stage 03 stage 07'nin ürettiği çerçeveyi OKUR (stageClarify.ts:2755); canlı "Kaleseramik → KS fabrika" governed-alias.</td><td>E4 KOD kalemleri: keşif kaynağı = <b>sahip-küratörlü tanımlayıcı, yönetişim yolundan</b> (yeni discovery sınıfı <code>curated</code>; listing tool zorunluluğu kalkar) · çerçeve bağlaması = yönetişimli nesne sözlüğü (satır 1, COMPANY) · ilan edilmiş-boş şirket katmanı HIGH RET DEĞİL: bilgi araçlarına düşer + not · <b>"stage 03 stage 07'den önce" = router LLM çağrısının AYRILMASI</b>: st02 çerçeve (LLM) → st03 çözüm → st07 getirme (LLM yok) → st07p plan (LLM) — A24 Sequence B'nin kendi sırası · KS alias'ının önceliği sahibin: şirket exact-match kazanır, fabrika alias'ı arşiv.</td><td>EK (K31 uzantısı)</td><td>scout D8 · S159-1</td><td>R6(c)</td></tr>
<tr class="a25row"><td>16</td><td>ALWAYS_INCLUDE + 'superset' literal'i</td><td>P4: ALWAYS_INCLUDE silinir; K17 literalsız giriş aracı; §3 giriş aracı kartı.</td><td>toolCategories.ts:1203–1205 iki ARMES aracı; assemble.ts:55 'superset' (scout: çit ihlali ŞİMDİ).</td><td><b>ÖNE ALMA:</b> hükümden bağımsız küçük kart ŞİMDİ — iki literal <code>tool_graph_node role=entry</code> + backends.pattern VERİSİNE taşınır (K17 türetiminin PROPOSAL yarısı); K17'nin sınıflayıcı ∩ readOnlyHint ∩ allowlist ∩ canary ∩ veto türetimi P1'de aynen.</td><td>ÖNE ALMA</td><td>scout S159-1 · Astra</td><td>R6(g)</td></tr>
<tr class="a25row"><td>17</td><td>Sabit kullanıcı metinleri</td><td>§13.9: b1_scope segmenti veri; P3 yeni segment sürümü, eval kapısı.</td><td>completionGuard.ts:228 "önce duruşlar, sonra fire" sabit; T2'de bir personel sorusuna basıldı.</td><td>Bütçe/fan-out metinleri ve benzerleri <code>prompt.segment</code> türünde tenant-editable veri olur (yeni segment sürümü, eval kapısı).</td><td>EK</td><td>T2 tanığı</td><td>—</td></tr>
<tr class="a25row"><td>18</td><td>SOTA iddiası</td><td>§9 SOTA-1 izlenebilirliği (Tier A–F).</td><td>—</td><td>SOTA §8/§9'un ÖLÇÜMÜYLE kurulur (bağımsız görevlerde daha doğru sonuç, kontrollü fatura, görülmemiş backend'e genelleme) — bileşen sayısıyla değil; "tanımlı görev alanında, belirtilen karşılaştırmalarda" iddiası; "her alanda en iyi" iddiası yok.</td><td>EK</td><td>Astra (son cevap)</td><td>—</td></tr>
</table>
<div class="a25box"><b class="h">A25'in DEĞİŞTİRMEDİĞİ (aynen yürürlükte):</b> K2–K5, K7–K9, K11–K16, K18–K20, K22–K31, §3 dokuz yüz ve durum makinesi, §4 Sequence A ①–⑭, §6 öğrenme yasası ("boş → öğrenme yok"; "BULMAYI iyileştirir, NE YAPTIĞINI asla"), §7 üç sınav, §9 P0–P5 sırası, K14 WRITE-GATED, PLATINUM. A25 hiçbir A24 kuralını daraltmaz; §Δ25 satırlarının her biri ya ekler ya sahip hükmüyle sapar.</div>
<div class="a25box"><b class="h">Sahibin hükmüne sunulanlar — OWNER-RULING-S160-ROUTING-V2-1 (tek yol önerileriyle):</b><br>
<b>R6(a)</b> OWNER-RULING-S140-K1-ORDER-CELL-HINT-1 ve IR-3 "MATRIX yerine geçer" kuralının geri alınması; OWNER-RULING-S151-K1-METRIC-HINTS-ALL-ACTIONS-1'in ipucu kuralı İPUCU sınıfı olarak yaşar, matris taşıyıcısı ölür. Öneri: EVET.<br>
<b>R6(b)</b> Yükümlülük göç varsayılanı: A · 154/169 anahtar kelimenin hepsi yükümlülük (p50 13, p90 46, max 56 yükümlü araç; taşma normal) — B · hepsi ipucu + merdiven tabanı, yükümlülük yalnız sahibin yayınladığı (koşul, araç) satırları. Öneri: <b>B</b>.<br>
<b>R6(c)</b> Şirket katmanı: küratörlü keşif kaynağı + COMPANY sözlük satırı + ilan-boş = ret değil + "Kaleseramik → KS fabrika" alias'ı ARŞİV (şirket kazanır). Öneri: EVET.<br>
<b>R6(d)</b> E1 üç-sağlayıcı taban ölçümü harcaması (held-out × 3; fatura maliyeti, önbellek durumu kaydedilir; tavan kartta). Öneri: ONAY.<br>
<b>R6(e)</b> ADR-008: çerçeve yalnız gözlem (K24 frame{}), süzgeç değil. Öneri: EVET (R6(a) ile aynı hüküm).<br>
<b>R6(f)</b> K1 Anthropic'te: A24 K1 her sağlayıcıya uygulanır; Anthropic geçişi E1 fatura sayısıyla kapılanır; o güne kadar PLAN yükümlülüğü. Öneri: EVET.<br>
<b>R6(g)</b> ALWAYS_INCLUDE + assemble.ts:55 → veri küçük kartı ŞİMDİ. Öneri: ONAY.</div>
</section>
'''
ins_before('<section id="sd">', delta25)

# ── §0 · legend + thesis ──────────────────────────────────────────────────────
ins_after('<span class="lg"><span class="sw rd"></span>bugünkü defekt · kaldırılan</span>',
          '\n<span class="lg"><span class="sw a25"></span><span class="a25b">A25 önerisi · kesikli kırmızı · rozetli</span></span>')
sec0_end = '</section>\n\n<section id="s1">'
ins_before(sec0_end, '''<div class="a25box"><span class="a25badge">A25</span><b class="h">Teze ek.</b> A24'ün tezi aynen durur. A25 üç şeyi ekler: (1) yönlendirme yolunda bir tenant'ın MES sözlüğü olarak yaşayan 6×13 MATRIX ve kapalı nesne/katman enum'ları YOK OLUR — çerçeve kalır, ama yalnız GÖZLEM ve K24 iz alanı olarak (OWNER-DESIGN-S159-1); (2) sahibin yayınladığı kurallar üç sınıfa ayrılır — yetki bağlayıcıdır, YÜKÜMLÜLÜK her sağlayıcıda değerlendirilir ve izle ölçülür, ipucu sıralar — ve olasılıksal seçim bu üçünün hiçbirini sessizce ezemez; (3) tek bir sağlayıcının yolu ("Anthropic'te her şey sunulur") A24 K1'in dışında kalamaz; geçiş fatura ölçümüyle kapılanır.</div>
''')

# ── §1 · measured state, S159 addendum ────────────────────────────────────────
ins_before('</section>\n\n<section id="s2">', '''<h3 class="sub a25"><span class="a25badge">A25</span>S159 · Yönlendirme yolunun ölçümleri (master 2a6f6781… → b8e5b1d9…; canlı DB; scout S159-1/S159-2; CWF-ASTRA-REVIEW-EVALUATION-S159-1)</h3>
<div class="a25box">
<b class="h">İki yol.</b> ANTHROPIC (stageTools.ts:551): kapsam içi TÜM araçlar ad sırasıyla sunulur ("cache mode, stable prefix"); kategori/router/matris/anahtar kelime koşmaz; çerçeve YOK (resolveTurnFrame.ts:172 absent ROUTING_BYPASS; ctx.irFrame yalnız :833'te süzgeçli dalda), stage 03 karanlık (stageClarify.ts:2764), planlayıcı bloğu yok. DİĞERLERİ: router LLM (kategori + çerçeve) → HIGH'da MATRIX yerine-geçme (deriveCategories.ts:63–92, :1620–1625) → matchCategories yalnız fallback (:1561/:1568), basis='frame' (:1644) ve sticky/önceki mesaj (:1681) — mevcut mesaj için semantik yolda KOŞMAZ (:1545–1557) → metrik ipuçları her eylemde ama frameRouting kapısının arkasında (:1609; kapı ipuçlarını, metrik tabanını, unmodeled keep/add'i, derived izi VE stage 03'ü birlikte kapatır) → ALWAYS_INCLUDE (:1203–1205) + assemble.ts:55 'superset' → bütçe dolunca sabit metin (completionGuard.ts:228). Son 185 stage-07 turunun 185'i <code>path</code> taşıyor: hepsi Anthropic dışı.<br>
<b class="h">Tanık T2 (personel sorusu, 2026-09-26 16:02:28Z):</b> path=semantic, basis=keyword, router [employee, production]; router'ın KENDİ çıktısında metricsSurface ["personel sayısı","çalışan sayısı"] — MKB'nin yayınlı anahtarları — ama derived.hints [] ve matchCategories koşmadı; 17 fabrika × getEmployeesWorkedBetween = 14 çağrı; 489.176 token; sabit "duruşlar/fire" metni; offeredByBackend'de honestbench ve mount-probe AYNI indeksleri [4,5,6,7] taşıyor (ad-temelli kimliğin canlı belirtisi). T1 sermaye (S158) · T3 Q3 fire (TARİHSEL, S151'de ipuçları eylemden bağımsız oldu) · T4: ARMES 50 dosya/71 eşleşme; MATRIX'e sıkı bağımlı 11 üretim + 8 test dosyası.<br>
<b class="h">Diğer ölçümler:</b> tool_experience yalnız censusToolDoc.ts:214 (seçim sonrası) ve toolCensusRefresh.ts:442 (offline) okur; censusToolDoc.ts:137–153 "used successfully in practice" cümlesini model-yüzlü açıklamaya ekler (toolCensus.composeEnabled taban 0, canlı UNMEASURED); sayaç oku-topla-upsert (ToolExperienceRepository.ts:110–150; eksik sayar, şişirmez) · learnToolMapping (:950–956) ve legacy (:1866) kapısız yazar, router.learnEnabled canlıda PUBLISHED 0 → fren AÇIK · toolRetrieval.ts:335 birleşim çıplak adla; stageTools.ts:1281 claimToolName ikinci sahibi reddeder (temizlenmiş ad: ikinci çakışma sınıfı) · governance.ts:427–434 golden kapısı yalnız prompt.segment · router.maxTools / maxFanout / maxSchemaTokens YOK; maxCategories=4 · kod tabanı 13 kategori / 154 anahtar kelime / 113 araç yuvası; 'tüketim' 42 araç, production 23, machine 21; fonksiyon kelimeleri anahtar ('neden', 'not', 'plan', 'alan', 'hat', 'miktar', 'hata', 'verim', 'canlı') · encoder.ts yer tutucu (dense = hash projeksiyon; sparse = 1+log(tf) sözlüksel, :15/:67–68), Qdrant iki prefetch + RRF (qdrantEngine.ts:510–527), pathB/bm25.ts yalnız varlık adları · cwf.trace.v1 kodda YOK · planner.ts deterministik PLAN bloğu, DAG değil; K26 onu "yeni mod" olarak uzatır (§13.1) · routeShadowLens kayıp hesaplar, kazanç hesaplamaz (:10–30); canlı semantik kol tekrar oynatılamaz.
</div>
''')

# ── §2 · decisions: inline red annotations + new K rows ───────────────────────
rep('<tr><td><b>K1</b> · Kilitli küçük set; tool_search ertelenmişleri açar</td>',
    """<tr><td><b>K1</b> · Kilitli küçük set; tool_search ertelenmişleri açar<br><span class="a25"><span class="a25badge">A25</span>bütçe parametreleri E2'de yaratılır (bugün yok); K1 HER sağlayıcıya — Anthropic geçişi fatura ölçümüyle (R6(f)); tool_search = <code>cwf_find_capability</code> (K32)</span></td>""")
rep('<tr><td><b>K9</b> · Kapsam kalibre küme; ham skor karar vermez</td>',
    """<tr><td><b>K9</b> · Kapsam kalibre küme; ham skor karar vermez<br><span class="a25"><span class="a25badge">A25</span>aynen; A25'in hiçbir "skor &gt; 0" ya da "sıra ≤ N" kuralı YOKTUR — kapsama K9, taban K17 (bütçeli küme)</span></td>""")
rep('<tr><td><b>K15</b> · TR BM25 analyzer zorunlu</td>',
    """<tr><td><b>K15</b> · TR BM25 analyzer zorunlu<br><span class="a25"><span class="a25badge">A25</span>aynen: E3 ablasyonu yalnız reranker/dense'i seçer (K16), BM25-TR'nin varlığını değil; bugünkü yer tutucu encoder E3'te değiştirilir</span></td>""")
rep('<tr><td><b>K17</b> · Giriş aracı ve sonda literalsız</td>',
    """<tr><td><b>K17</b> · Giriş aracı ve sonda literalsız<br><span class="a25"><span class="a25badge">A25</span>aynen; ÖNE ALMA: ALWAYS_INCLUDE + assemble.ts:55 literalleri ŞİMDİ veriye (role=entry + backends.pattern) — türetim (sınıflayıcı ∩ readOnlyHint ∩ allowlist ∩ canary ∩ veto) P1'de (R6(g))</span></td>""")
rep('<tr><td><b>K21</b> · Dual-card ve sürümlenmiş bütün</td>',
    """<tr><td><b>K21</b> · Dual-card ve sürümlenmiş bütün<br><span class="a25"><span class="a25badge">A25</span>aynen; demet = mevcut kind'lar üzerinde hash + atomik işaretçi (yeni tablo YOK, 12.6); grup geri alma = demetin geri alınması (Astra D13, A24'ün kendi K21'inin sonucu)</span></td>""")
rep('<tr><td><b>K24</b> · İz şeması dondurulur</td>',
    """<tr><td><b>K24</b> · İz şeması dondurulur<br><span class="a25"><span class="a25badge">A25</span>v1 kodda hiç inşa edilmedi; A25 v1'i İNŞA eder ve adlandırılmış sürüm artışıyla v2'ye uzatır (K35); v1 alanları aynen</span></td>""")
k_rows = '''
<tr class="a25row"><td><span class="a25badge">A25</span><b>K32</b> · Yönetişimli veri üç sınıf; <code>routing_obligation</code> (koşul, ARAÇ)</td><td>Yetki (K10) bağlayıcı · YÜKÜMLÜLÜK: sahibin yayınladığı (koşul, araç) satırı — süzgeçli yolda sunulan kümeye girer, K1 bütçesine ÖNCE sayılır; Anthropic'te PLAN kısıtı (st07p çağırır ya da nedenini yazar; iz <code>obligation_honoured</code>); yalnız yükümlülükler bütçeyi aşarsa <code>OBLIGATION-OVERFLOW</code> damgası, sahip Kurallar sekmesinde görür · İPUCU: mevcut anahtar kelimeler, metrik ipuçları, tahmini katman, sticky = sıralama kanıtı + A24 P4 merdiven tabanı (bugünkü fallback aynen). Değişmez: her geçerli ipucu HER yolda ve HER sağlayıcıda değerlendirilir, etkisi izde (<code>governedKept</code> = her kesimden sonra ÖLÇÜLEN özellik, sıralama vaadi değil); hiçbir ipucu yetkiyi aşmaz; aday olmak sunulmayı zorunlu kılmaz. Göç varsayılanı HİNT (R6(b)); LEARNED eşlemeler asla yükümlülüğe göçmez. Sayılar §1.</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span><b>K33</b> · Araç kimliği server_id + backend_id + tool</td><td>K6'nın uzantısı: getirme birleşimi (toolRetrieval.ts:335), kayıt (claimToolName), deneyim/iz ve kartlar bu üçlüyle anahtarlanır; model-yüzlü ad türetilir, çakışmasız; T2'nin honestbench/mount-probe çakışması E2'nin ilk kırmızı testi. MCP 2025-06-18: <code>name</code> "unique identifier for the tool"; tools/call sunucu oturumuna adreslidir → sunucular arası benzersizlik istemcinin (bizim) işidir.</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span><b>K34</b> · Yayın kapısı her yönetişimli türe</td><td>decideGoldenPublish (governance.ts:434, bugün yalnız PROMPT_SEGMENT) tool_category · routing_obligation · ranking_policy · tool_profile · kart demeti için de kapı olur — KABLOLAMA (12.6). Kapı = K23 süzgeci + yönlendirme ∧ erişim sınavı + K25 aralığı + canary; yayın K21 demeti; geri alma demeti geri alır. Sıralama öncelikleri (<code>ranking_policy</code>) YAYINLANMIŞ veridir; çalışma zamanı öğrenilmiş ağırlık yoktur (top-k içinde sıra değişimi sunulan kümeyi değiştirir → kapıdan geçer).</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span><b>K35</b> · cwf.trace.v2 = v1 + alan haritası; etiketler ayrı</td><td>v1 (§7b) inşa edilir ve v2'ye uzatılır: araç başına <code>candidate · offered · selected · sent · reason(authority-pass|obligation|base-set|retrieval-rank|conformal|hint|layer|sticky|ladder-floor|discovery)</code> · <code>governedKept</code> · <code>obligation_honoured</code> · <code>catalog_version</code> · <code>policy_version</code>. APPEND-ONLY; tur SONRASI etiketler (K23 konjonksiyonu, kullanıcı düzeltmesi, tekrar soru) trace_id ile anahtarlı AYRI etiket kaydında; <code>result_class</code> sözlüğü v1'inki. tool_experience bu izin GÖRÜNÜMÜ olur ya da emekli edilir (oku-topla-upsert yarışı yapısal olarak biter).</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span><b>K36</b> · Keşif zinciri <code>cwf_find_capability</code></td><td>K1'in tool_search'ü, sağlayıcı-agnostik (A24 §10 açık soru 2'nin cevabı): ara → yetkili kart (K21 demeti) → güncel şema → kayıt (K33 kimliğiyle) → BİR SONRAKİ model adımında kullanılabilir; K10'un tools/call yeniden kontrolü, "kapsam eşleşmesi çağrı yetkisi vermez" ve "kapsam değişince indeks/önbellek/LEARNED geçersiz" tur-içi kayda BAĞLANIR; gateway'in <code>search_tools</code>ünden ayrı kimlik. Her kullanım INITIAL-NEED-MISS (kaçırma defteri) ya da NEXT-STEP-DISCOVERY; yalnız ilki §6 taban-küme önerisine girer.</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span><b>K37</b> · Sağlayıcı sunum matrisi; K1 Anthropic'te</td><td>Sunulan küme sağlayıcı başına TANIMLIDIR ve K1 hepsine uygulanır. Bugünkü Anthropic tam-katalog önbellek yolu A24'ün dışındadır; süzgeçli yola geçiş E1'in FATURA ölçümüyle (önbellek durumu kaydedilir; Toollery App. B.2: görünür token azalması fatura tasarrufu değildir) kapılanır (R6(f)); geçişe kadar yükümlülük PLAN yükümlülüğüdür ve yükümlü araçların şema/özetleri önbellek ön-ekinde SABİT kalır. Çerçeve ve stage 03 o yolda bugün karanlıktır → E4 (K39) açar. Tam-katalog yolu lab bayrağı olarak kalır.</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span><b>K38</b> · Kart yüzleri: TOPLULAŞTIRMA ve KAPSAM</td><td>TOPLULAŞTIRMA: ölçü, birim, grain, tekrar-giderme anahtarı (aynı kişi iki fabrikada), zaman semantiği ("bugün aktif" ≠ "dönemde çalıştı" ≠ FTE), kapsama damgası — planlayıcı doğru aracı bulsa bile yanlış iş sonucunu bu yüz önler. KAPSAM (bilgi araçları): kaynak envanterinden türetilen konu/dönem/kurum kapsamı — "sermaye nedir?" sorusu "dokümanlarda RAG arar" açıklamasına değil kapsam yüzüne eşleşir; K22'nin pozitif yarısı. Provenance sözlüğü §3'ünki.</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span><b>K39</b> · Router çağrısının ayrılması; şirket katmanı</td><td>"Stage 03 stage 07'den önce" bir yeniden sıralama değil, bugünkü TEK router çağrısının (kategori + çerçeve) AYRILMASIDIR: st02 çerçeve (LLM) → st03 çözüm (deterministik, K31) → st07 getirme (LLM yok) → st07p plan (LLM) — A24 Sequence B'nin kendi sırası. Şirket katmanı: keşif kaynağı = sahip-küratörlü tanımlayıcı (discovery sınıfı <code>curated</code>; listing tool zorunluluğu kalkar) · çerçeve bağlaması = yönetişimli nesne sözlüğü (COMPANY satırı; §Δ25 #1) · ilan edilmiş-boş şirket katmanı HIGH RET DEĞİL (bilgi araçlarına düşer + not) · "Kaleseramik → KS fabrika" alias'ının önceliği sahibin (R6(c)). K31'in "her düğüm izde; descendant walk yalnız çok-katmanlı ifadeler için" cümlesi aynen.</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span><b>K40</b> · Üreticiler ayrı; frenler adıyla</td><td>Niyet-sorgusu üreticisi (Toollery; kart verisi, retrieval indeksine; kapılı) ≠ sınav paraphrase üreticisi (K11) ≠ profilleyici (K3, Sequence A ⑦); üretilmiş hiçbir metin held-out'a girmez. Frenler E5'e kadar AÇIK: learnToolMapping (learnEnabled=0) · legacy :1866 · toolCensus.composeEnabled (model-yüzlü deneyim cümlesi); E5'te olay yoluna (K35) taşınır. Sabit kullanıcı metinleri (completionGuard.ts:228) <code>prompt.segment</code> verisi olur.</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span><b>K41</b> · MATRIX ve kapalı enum'lar yönlendirme yolundan çıkar</td><td><span class="a25del">deriveCategories MATRIX yerine-geçme</span> P4/E5'te silinir; o güne kadar <code>router.matrixReplace=0</code> ile hükümsüz (E2 anahtar ayrımı: <code>router.matrixReplace</code> ≠ <code>router.frameEnabled</code> ≠ "keyword semantik yolda"). IR_OBJECTS kapalı enum → yönetişimli sözlük (veri, COMPANY ilk satır); alias katman enum'u backend_entity_layers'tan; arg-policy satırı katman-agnostik. Çerçeve GÖZLEM ve K24 iz alanı olarak kalır; planner.ts'in IrAction anahtarları sözlüğü okur (organ korunur, §13.1). Kırmızıya dönmesi GEREKEN testler E5 kartında dosya adıyla (11 üretim + 8 test dosyası, kesimde yeniden ölçülür). Sahip hükmü R6(a)/(e).</td></tr>
'''
ins_before('</table>\n<div class="note bl"><b>Bilinçli redler', k_rows)

# ── §3 · cards ────────────────────────────────────────────────────────────────
rep('<div class="card am"><h4>Kimlik ve durum makinesi</h4><div class="k">backends · <span class="new">yeni alanlar</span></div>',
    '<div class="card am"><h4>Kimlik ve durum makinesi</h4><div class="k">backends · <span class="new">yeni alanlar</span> · <span class="a25b">A25: server_id + backend_id + tool kimliği (K33)</span></div>')
cards_a25 = '''
<div class="card a25c"><h4><span class="a25badge">A25</span>Toplulaştırma yüzü</h4><div class="k">aggregation · kart verisi · K38</div>ölçü · birim · grain · tekrar-giderme anahtarı (aynı kişi iki fabrikada) · zaman semantiği ("bugün aktif" ≠ "dönemde çalıştı" ≠ FTE) · kapsama damgası. Provenance: DERIVED / LEARNED / CURATED. Planlayıcı (K26) toplama operatörünü buradan okur; "aggregate-capability: true" bayrağı yeterli DEĞİLDİR.</div>
<div class="card a25c"><h4><span class="a25badge">A25</span>Kapsam yüzü (bilgi araçları)</h4><div class="k">coverage · korpus sondasından türetilir · K22'nin pozitif yarısı · K38</div>konu · dönem · kurum kapsamı — kaynak envanterinden; modelin varsayımı olarak doğmaz. "Şirket sermayesi nedir?" bu yüze eşleşir. Kısmi envanter → UNMEASURED (K22).</div>
<div class="card a25c"><h4><span class="a25badge">A25</span>Yükümlülük ve sıralama politikası</h4><div class="k"><code>routing_obligation</code> (koşul, ARAÇ) · <code>ranking_policy</code> · YENİ yönetişimli türler · K32/K34</div>Sahibin yayınladığı satırlar; kapıdan (K34) geçer; K21 demetinin parçası; geri alma demetle. Mevcut anahtar kelime satırları İPUCU olarak kalır (A24 P4 merdiven tabanı).</div>
'''
ins_before('</div>\n<h3 class="sub">Durum makinesi', cards_a25)

# ── SVG 1 · state machine: red note ───────────────────────────────────────────
svg_close_1 = html.find('</svg>')
html = html[:svg_close_1] + '''<g><rect class="a25s" x="20" y="212" width="960" height="30" rx="6"/><text class="a25t" x="30" y="231">A25 · K21 demeti = mevcut kind'lar üzerinde hash + atomik işaretçi; yeni tablo YOK (12.6) · yayın kapısı (K34) her tür için · etiketler ayrı kayıtta (K35)</text></g>
''' + html[svg_close_1:]

# ── SVG 2 · Sequence A: red band at the bottom (extend viewBox) ───────────────
rep('<svg viewBox="0 0 1240 1300" role="img" aria-label="Sequence A — yeni backend bağlanma sequence diyagramı (v1_3)">',
    '<svg viewBox="0 0 1240 1560" role="img" aria-label="Sequence A — yeni backend bağlanma sequence diyagramı (v1_3) + A25 kırmızı ekleri">')
pos = [m.start() for m in re.finditer('</svg>', html)][1]
band_a = [
 ("t","A25 · Sequence A'ya EKLER (A24 ①–⑭ aynen; kırmızı = öneri; OWNER-RULING-S160-ROUTING-V2-1 bekler)"),
 ("m","④′ ayna: araç kimliği server_id + backend_id + tool (K33; K6 uzantısı) — çıplak ad birleşimi ve claimToolName reddi biter;"),
 ("m","    sanitize çakışması ikinci sınıf olarak izde (T2'de honestbench/mount-probe aynı indeksleri taşıyordu)"),
 ("m","⑦′ profil: TOPLULAŞTIRMA ve KAPSAM yüzleri (K38) türetilir · niyet-sorgusu üreticisi ≠ profilleyici ≠ sınav üreticisi (K40);"),
 ("m","    üretilmiş hiçbir metin held-out'a girmez (K11)"),
 ("m","⑨′ kodlama: BM25-TR zorunlu (K15) + dense — gerçek encoder; bugünkü hash yer tutucusu E3'te değişir (K16 ablasyonu yalnız reranker/dense'i seçer)"),
 ("m","    giriş aracı K17 aynen; ALWAYS_INCLUDE + assemble.ts:55 literalleri ŞİMDİ veriye (role=entry + backends.pattern; R6(g))"),
 ("m","⑩′ sınav: K-A fikstürü = repoda tools/list'i JSON'dan servis eden sentetik MCP sunucusu (finans, 30 araç) + K-A′ ikinci görülmemiş-sözlüklü backend;"),
 ("m","    K-G aleti (ARMES grep 0 — gerekli, yeterli değil); K11 üç küme + E2E N=10 gece sınavı aynen"),
 ("m","⑫′ erişim: keşif zinciri (K36) ile tur içinde kaydedilen araç da aynı reach sınıfına tabidir; K10'un tools/call yeniden kontrolü tur-içi kayda bağlı"),
 ("m","⑬′ yayın: decideGoldenPublish her yönetişimli tür için (K34; bugün yalnız prompt.segment) · sahibin yükümlülük satırları (K32) aynı kapıdan · demet geri alma (K21)"),
]
y = 1312
parts = ['<g>', '<rect class="a25s" x="10" y="1290" width="1215" height="255" rx="8"/>']
for kind, txt in band_a:
    parts.append(f'<text class="a25{kind}" x="22" y="{y}">{txt}</text>')
    y += 22 if kind == 't' else 18
parts.append('</g>\n')
html = html[:pos] + '\n'.join(parts) + html[pos:]

# ── SVG 3 · Sequence B: red overlays + red band ───────────────────────────────
rep('<svg viewBox="0 0 1100 560" role="img" aria-label="Planlayıcı ve yürütücü döngüsü">',
    '<svg viewBox="0 0 1100 870" role="img" aria-label="Planlayıcı ve yürütücü döngüsü + A25 kırmızı ekleri">')
pos = [m.start() for m in re.finditer('</svg>', html)][2]
badge = lambda x, y, n: (f'<rect class="a25l" x="{x}" y="15" width="{n}" height="56" rx="9"/>'
                         f'<rect x="{x+n-34}" y="8" width="34" height="14" rx="4" fill="#D00000"/>'
                         f'<text x="{x+n-17}" y="19" text-anchor="middle" style="fill:#fff;font:700 9px ui-monospace,monospace">A25</text>')
band_b = [
 ("t","A25 · Sequence B'ye EKLER (A24 ①–⑤ ve st09–st13 aynen; kırmızı = öneri; OWNER-RULING-S160-ROUTING-V2-1 bekler). Rozetli kutular: A25'in dokunduğu organlar."),
 ("m","IR Router (st02) → A25: çerçeve yalnız GÖZLEM ve K24 iz alanı; MATRIX yerine-geçme yok (K41); nesne sözlüğü veri (+COMPANY); tek router çağrısı ayrılır (K39)"),
 ("m","Retriever+Slot+Scope (st03′·st07) → A25 L1 sırası: (0) yetki K10 → (a) YÜKÜMLÜLÜKLER (koşul, ARAÇ) K32 → (b) K1/K17 bütçeli TABAN"),
 ("m","    (cwf_find_capability + kullanım-sıklığı top-N giriş) → (c) K2 hibrit getirme (iki korpus, BM25-TR K15) → (d) K9 KONFORMAL küme (α 0.10; n_min 30;"),
 ("m","    kalibre değilken sunar; ham skor karar vermez) → (e) İPUÇLARI sıralama kanıtı → (f) MERDİVEN TABANI (router susar / vektör düşer →"),
 ("m","    anahtar kelime kategorileri sunulan kümeyi belirler, bugünkü fallback aynen; A24 P4)"),
 ("m","    bütçe: router.maxTools + maxSchemaTokens (E2'de yaratılır) · doldurma: yükümlülük → taban → sıralı aday · OBLIGATION-OVERFLOW damgası · governedKept ÖLÇÜLÜR (K35)"),
 ("m","    şirket katmanı stage 03'te (K39): küratörlü keşif kaynağı; ilan-boş = ret değil; \"Kaleseramik → KS fabrika\" alias önceliği sahibin (R6(c))"),
 ("m","Planlayıcı (st07p) → A25: turn/planner.ts'in YENİ MODU (§13.1); plan yükümlü aracı kapsar ya da nedenini yazar (obligation_honoured);"),
 ("m","    kart TOPLULAŞTIRMA yüzünü okur (K38); eksik halka → cwf_find_capability (K36) → kayıt → SONRAKİ adım; Anthropic'te yükümlülük = PLAN kısıtı (K37)"),
 ("m","Yürütücü → A25: gerekli fan-out KODDA, paralel, router.maxFanout bütçeli; toplama kodda; modele TEK sonuç tablosu (T2'nin 489.176 token'ı girmez);"),
 ("m","    durmak yetenek değil — aggregate / batch / sayfalama / bütçeli paralel seçimi izde"),
 ("m","İz → cwf.trace.v2 (K35): araç başına candidate/offered/selected/sent/reason · governedKept · obligation_honoured · catalog_version · policy_version;"),
 ("m","    tur sonrası etiketler ayrı kayıtta; tool_experience = görünüm · sabit bütçe metni → prompt.segment (K40)"),
 ("m","Sağlayıcı → aynı yetki ve yükümlülük üç sağlayıcıda; Anthropic tam-katalog yolu E1 FATURA ölçümüne kadar (K37, R6(f)); bugün o yolda çerçeve ve stage 03 yok"),
]
y = 567
parts = ['<g>', badge(205, 15, 160), badge(395, 15, 180), badge(605, 15, 150), badge(785, 15, 150),
         '<rect class="a25s" x="10" y="545" width="1080" height="315" rx="8"/>']
for kind, txt in band_b:
    parts.append(f'<text class="a25{kind}" x="22" y="{y}">{txt}</text>')
    y += 24 if kind == 't' else 18
parts.append('</g>\n')
html = html[:pos] + '\n'.join(parts) + html[pos:]

# ── §5 · red note after the "bugünkü akışta" note ─────────────────────────────
ins_before('</section>\n\n<section id="s6">', '''<div class="a25box"><span class="a25badge">A25</span><b class="h">S159'da aynı sınıf nerede düştü (ÖLÇÜLDÜ).</b> T2 personel sorusu: router kendi çıktısında MKB'nin yayınlı anahtarlarını gördü (metricsSurface) ve yine de MKB'yi sunmadı — çünkü semantik yolda mevcut mesaj için anahtar kelime eşleyici hiç koşmaz ve metrik ipuçları yalnız registry'nin bildiği metrikler için ateşler; 17 fabrikaya tek tek gitti, bütçe doldu, sabit metin bastı. A25'te aynı soru: yetki → (sahip yayınladıysa) yükümlülük "personel sayısı → mkb.knowledge_search" → taban → hibrit getirme (kart KAPSAM yüzü "personel/insan kaynakları/faaliyet raporu" ile eşleşir) → konformal küme {mkb, armes} → plan: knowledge_search(query) ∥ (gerekirse) getEmployeesWorkedBetween × N fabrika → yürütücü toplar (TOPLULAŞTIRMA yüzü: count_distinct kişi, dönem semantiği) → tek tablo → st12 her sayı baytta. Anthropic'te: aynı yükümlülük plan kısıtı olarak.</div>
''')

# ── §6 · self-learning additions ──────────────────────────────────────────────
ins_before('</section>\n\n<section id="s7">', '''<div class="a25box"><span class="a25badge">A25</span><b class="h">§6'ya ekler (A24 satırları aynen).</b> (1) Öğrenmenin GİRDİSİ cwf.trace.v2 olayıdır (K35), tool_experience sayacı değil; K23 konjonksiyonu tur SONRASI etiket kaydında hesaplanır; "kullanıcı tekrar sordu" tek başına etiket değildir; grounding geçmek tek başına doğruluk değildir. (2) ÖNERİ türlerine "sıralama önceliği" (<code>ranking_policy</code>, K34 kapısından) ve "yükümlülük adayı" (sahibe öneri; sahip yayınlar) eklenir; "araç BİRLEŞTİRME" önerisi YOKTUR (A24 kırmızı çizgisi: öğrenme neyi BULDUĞUNU iyileştirir, ne YAPTIĞINI asla). (3) LEARNED eşlemeler (tool_cache) asla yükümlülüğe dönüşmez. (4) Frenler E5'e kadar: learnToolMapping · legacy :1866 · toolCensus.composeEnabled (K40). (5) tool_search kullanımı yalnız INITIAL-NEED-MISS sınıfındaysa taban-küme önerisine girer (K36). (6) BaRP tarzı bandit ilkesi LLM yönlendirmesi literatürüdür; burada HİPOTEZ olarak durur, E5'te ölçülmeden politika olmaz.</div>
''')

# ── §7b · trace v2 field map ──────────────────────────────────────────────────
ins_before('</section>\n\n<section id="s8">', '''<h3 class="sub a25"><span class="a25badge">A25</span>§7c · cwf.trace.v2 — v1'in alan haritası (K35; v1 alanları AYNEN, eklemeler kırmızı)</h3>
<div class="frame" style="border:2px dashed var(--a25)">cwf.trace.v2  = cwf.trace.v1 (yukarıdaki her alan, aynen)  +
  <span style="color:#FF8A80">tools[]{server_id,backend_id,tool,candidate,offered,selected,sent,reason(authority-pass|obligation|base-set|retrieval-rank|conformal|hint|layer|sticky|ladder-floor|discovery)}</span>
  <span style="color:#FF8A80">governedKept(count,of) · obligation_honoured[]{obligation_id,honoured,reason} · overflow(OBLIGATION-OVERFLOW|none)</span>
  <span style="color:#FF8A80">catalog_version · policy_version · provider · offer_mode(filtered|full-catalogue-cache|lab-bypass) · frame_source(st02|absent)</span>
  <span style="color:#FF8A80">discovery[]{query,hits,registered,class(INITIAL-NEED-MISS|NEXT-STEP-DISCOVERY)}</span>
<span class="c">// APPEND-ONLY. Tur SONRASI etiketler AYRI kayıtta: trace_label{trace_id, k23{answered,grounded,cited,no_correction,no_pii,not_empty}, user_correction, re_ask, labelled_at} — iz satırı değişmez.</span>
<span class="c">// tool_experience = bu izin görünümü (VIEW) ya da emekli; oku-topla-upsert yarışı yapısal olarak biter.</span></div>
''')

# ── §8 · traps additions ──────────────────────────────────────────────────────
ins_before('</section>\n\n<section id="s9">', '''<div class="a25box"><span class="a25badge">A25</span><b class="h">§8'e eklenen tuzaklar (S159'da ölçüldü).</b> <b>Sağlayıcı ayrımı</b> — bir sağlayıcının yolu (tam katalog) mimarinin dışında yaşar ve ölçüm onu görmez → K37, K1 hepsine · <b>Çıplak ad kimliği</b> — iki backend'in aynı adlı aracı sessizce tek araç olur → K33 · <b>Tek türe kapı</b> — yayın kapısı yalnız prompt.segment'i korur, anahtar kelime/politika sınavsız yayınlanır → K34 · <b>Anahtar kelime = yükümlülük</b> — her yayınlı kelimeyi bağlayıcı yapmak bütçeyi normal durumda taşırır (p90 46) → K32 (koşul, ARAÇ; varsayılan ipucu) · <b>Çerçeve olmayan yol</b> — Anthropic'te çerçeve/stage 03/planlayıcı yok → K37/K39 · <b>Alıntı yerine özet</b> — bir tasarım belgesi dayandığı kuralı numarayla anarsa daraltır (A-REC-S159-2/3) → A25 A24'ü bayt bayt taşır · <b>Bir kapısız fren</b> — kapısız öğrenme kodda var, fren canlı bir parametre (learnEnabled=0) → frenler adıyla, E5'e kadar (K40) · <b>Görünür token ≠ fatura</b> — önbellek altında token azalması maliyeti orantılı düşürmez (Toollery B.2) → E1 fatura ölçümü.</div>
''')

# ── §9 · transition: red E1–E5 rows inside P0–P5 ─────────────────────────────
# find the §9 table end: the first '</table>' after '<section id="s9">'
s9 = html.find('<section id="s9">')
t_end = html.find('</table>', s9)
assert t_end > s9
e_rows = '''
<tr class="a25row"><td><span class="a25badge">A25</span>E1</td><td>P0/P1'in sınav yarısına: K11 üç küme held-out gerçek turlardan; kabul edilebilir küme etiketleri; dört tanık (T1 sermaye · T2 personel · T3 Q3 fire · PR 621 camelCase) REGRESYON kümesi, final değil; K-A fikstürü (sentetik MCP sunucusu, finans, 30 araç) + K-A′ ikinci görülmemiş sözlük; K-G aleti; ÜÇ SAĞLAYICI tabanı fatura maliyetiyle (önbellek durumu kaydedilir; harcama R6(d)); K25 barajı BU AŞAMADA ilan. Kod: yalnız replay/sınav/fikstür.</td><td>Taban sayıları provider × backend kırılımlı; hiçbir eşik uydurulmadı.</td><td>—</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span>E2</td><td>P1'in kart yarısına: K33 kimliği (ilk kırmızı test: T2 çakışması) · routing_obligation + ranking_policy türleri (K32/K34) · K38 yüzleri · cwf.trace.v2 inşası + etiket kaydı (K35) · router.maxTools / maxSchemaTokens / maxFanout yaratılır (K1) · anahtar ayrımı router.matrixReplace ≠ router.frameEnabled ≠ keyword-semantik (K41) · decideGoldenPublish genelleştirmesi (K34) · tool_experience → görünüm · sabit metinler → prompt.segment (K40).</td><td>Sözleşme testleri; kapısız yayın imkânsız (test); demet geri alma testi; iz satırı değişmezliği testi.</td><td>—</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span>E3</td><td>P2'ye: kollar KAYITLI router çıktısı üzerinde (kayıtlı-sunulan · matris kapalı · keyword her yolda · BM25-TR · dense gerçek encoder · hibrit RRF · +reranker K16); iki göç varsayılanının OBLIGATION-OVERFLOW sıklığı; K9 kalibrasyon adayı; canlı semantik kol tekrar oynatılamaz → yalnız E1 offline sınavla karşılaştırılır.</td><td>Kazanan ölçümle (K16); frameRouting/matrixReplace flip'i sahiple arayüzden, K34 kapısıyla.</td><td>—</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span>E4</td><td>P1-B/P3'e: router çağrısının ayrılması (K39) · şirket katmanı kod kalemleri · st07p = turn/planner.ts yeni modu + yürütücü v0 (aggregate_records) + bütçeli fan-out (K26) · keşif zinciri üç sağlayıcıda (K36) · sağlayıcı matrisi ve önbellek ön-eki (K37).</td><td>T2 tek tablo, ≤ router.maxFanout çağrı, sayılar yürütücü baytında; yeni keşfedilen araç aynı turda kullanılabilir; Anthropic'te obligation_honoured ölçülür.</td><td>—</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span>E5</td><td>P4/P5'e: olay → K23 → öneri → K34 kapısı → canary → K21 yayın → geri alma; frenler olay yoluna; <span class="a25del">MATRIX + IR süzgeç enum'ları + alias enum'u</span> silinir, hand category rows arşivlenir (A24 P4 aynen); kırmızı test listesi kartta dosya adıyla.</td><td>A24 P4/P5 çıkışları + K-A/K-A′ yeşil + K-G 0.</td><td>MATRIX · IR süzgeç enum'ları · alias enum'u</td></tr>
<tr class="a25row"><td><span class="a25badge">A25</span>ŞİMDİ</td><td>Hükümden bağımsız (R6(g)): ALWAYS_INCLUDE + assemble.ts:55 → veri (küçük kart, scout: çit ihlali şimdi). Her kart → scout → şerit → PR → sınav sayıları raporda → scout iniş → master; 30 dakika = yeşil dal → master gecikmesi (12.8), aşama boyu değil.</td><td>Vercel prod READY + iz.</td><td>iki literal</td></tr>
'''
html = html[:t_end] + e_rows + html[t_end:]

# ── §10 · contributions / A-REC / open questions / dropped claims ─────────────
ins_before("""<h3 class="sub">Architect'in hataları (A-REC, mekanizma olarak)</h3>""", '''<div class="a25box"><span class="a25badge">A25</span><b class="h">S159 katkıları, adıyla (S112-YASA-1 · §12.14).</b> <b>SAHİP — OWNER-DESIGN-S159-1</b> (2026-09-26 19:16 TSİ): "6×13 hard-kodlu çerçeve matrisi ve kodun içine sokulmuş sabit bloklar mimariyi çöpe çeviriyor; yeni bir backend (finans) eklediğimde bu tablo her şeyi ARMES'e çevirecek; kendi kendine öğrenen, konfigüre olan, iyileşen yapı şart; kod öncesi doküman + plan + scout tartışması"; ayrıca ChatGPT Astra incelemesinin toplanması ve A25'in "kırmızı fark" biçimi (27 Eylül 03:32 TSİ). <b>ASTRA — EXT-DESIGN-S159-ASTRA-1</b>: üç sınıf yönetişimli veri (K32), sağlayıcı matrisi (K37), araç kimliği (K33), kapı genelleştirmesi (K34), keşif zinciri (K36), yönlendirme olayı (K35), toplulaştırma/kapsam yüzleri (K38), çalışma zamanı bütçesi, kanıt aşamaları, kabul tablosu, kapsamlı sıfır-kod; 24 maddenin 21'i ölçümle kabul, 0 ret (CWF-ASTRA-REVIEW-EVALUATION-S159-1). <b>SCOUT S159-1/S159-2</b>: kapısız learnToolMapping; Anthropic'te çerçeve/stage 03 yok; router.maxTools yok; yükümlülük taşma sayıları; şirket katmanının stage 03'ü nasıl kırdığı (router çağrısının ayrılması); cwf.trace.v1'in inşa edilmemişliği; E3 kollarının koşturulamazlığı; composeEnabled kanalı; literatür alıntıları (ToolScope dense+reranker ve yeniden etiketleme; Toollery fatura). <b>ARCHITECT</b>: A24'ün bayt bayt taşınması mekanizması; K32'nin göç varsayılanı çerçevesi; K39'un "A24 Sequence B zaten bu sırayı söylüyor" okuması.</div>
''')
ins_before('<h3 class="sub">Açık sorular</h3>', '''<div class="a25box"><span class="a25badge">A25</span><b class="h">A-REC-S159-1</b> · Üç oturum boyunca yönlendirme dikişi yamalandı (PR 620, keyword-floor kartı) — A24 §10 "kelime listesi yönlendiricisi kaldırıldı" hükmü dururken; sahip yapıyı adıyla söyledi. <b>A-REC-S159-2</b> · Yönlendirme taslağı v1 A24'ü yalnız K-numarasıyla taşıdı ve dört yerde tersini yazdı (3 boş → ceza; "plan, bütçe değil"; satır düzeyi geri alma; "skor &gt; 0"). Dış inceleme A24'ü görmeden yakaladı. <b>A-REC-S159-3</b> · v2 "inline ettim" diyerek A24'ü PARAFRAZ etti: 16 kuralın 12'si daraldı (scout). Kural: bir tasarım belgesi dayandığı kuralı MAKİNEYLE, satır numarasıyla, bayt bayt alıntılar — A25 bu yüzden A24 v1_3 HTML'inin kendisi üstüne kurulur; el yazısı özet alıntı değildir (12.4'ün belge genişliğinde hâli).</div>
''')
ins_after('<h3 class="sub">Açık sorular</h3>\n<ol>', '''
<li class="a25"><span class="a25badge">A25</span><b>R6(a)–(g)</b> — §Δ25'teki yedi hüküm sorusu; hiçbiri hükmedilmeden yönlendirme yoluna kod dokunmaz (S102-YASA-3).</li>
<li class="a25"><span class="a25badge">A25</span><b>Yükümlülük koşul dili</b> — mesaj deseni / çerçeve alanı / varlık katmanı / sağlayıcı; ilk sürüm yalnız mesaj deseni + çerçeve alanı; sahip arayüzden yazar; E3 taşma ölçer.</li>
<li class="a25"><span class="a25badge">A25</span><b>Anthropic geçiş eşiği</b> — E1 fatura ölçümü hangi farkta geçişi haklı çıkarır: sayı E1'den önce yazılmaz (K25 ruhu).</li>''')
rep("""<h3 class="sub">Tekrar edilmeyecek iddialar (v1'den düşenler)</h3>""",
    """<h3 class="sub">Tekrar edilmeyecek iddialar (v1'den düşenler)</h3>\n<div class="a25box"><span class="a25badge">A25</span><b class="h">S159'da düşenler:</b> "BM25-TR + dense zaten hazır" (encoder yer tutucu; sparse 1+log(tf)) · "tool_experience'ın tüketicisi yok" (census/doc okuyor; seçim yolu okumuyor) · "metrik ipuçları yalnız QUERY_METRIC'te" (S151'de düzeldi) · "ToolScope BM25+dense üstünlüğünü kanıtladı" (ana deney dense + cross-encoder; etiketler yeniden eşlendi) · "Toollery BM25 .942 vs embed+rerank .704" (aynı koşul değil; ham spec BM25 .571; BFCL-V4'te BM25 .948 &lt; RAGAnything .980) · "%98 bağlam / 30–50 araç" mühendislik sabiti değildir · "skoru sıfırdan büyük her backend'in giriş aracı" (RRF her zaman pozitif; K9/K17 yeter) · "3 kez boş → ceza" (A24 öğrenme yasasına aykırı) · "fan-out planla önlenir, bütçeyle değil" (K26 ikisini de ister) · "şirket katmanı yalnız veri" (IR enum'u, alias enum'u, arg-policy, discovery_tool NOT NULL: kod işi) · "resolveTurnFrame her yolda çerçeve verir" (çağrı her yolda, çerçeve Anthropic'te absent).</div>\n<h3 class="sub">A24'ün kendi listesi:</h3>""")

# ── footer ────────────────────────────────────────────────────────────────────
rep('<footer>END · A24_cwf-capability-fabric-architecture-v1_3',
    f"""<footer><span class="a25b">END · A25_cwf-capability-fabric-architecture-v1 · rev 1.0 · {NOW} · S159/S160 · A24 v1_3 bayt bayt korundu (sha256 {A24_SHA}) · kırmızı = A25 önerisi · OWNER-RULING-S160-ROUTING-V2-1 bekler · doc v3 (CWF-ROUTING-ARCHITECTURE-v2-DRAFT-S159-3) ve scout S159-1/S159-2 hükümleri girdi</span><br>Altta A24 v1_3'ün kendi bitiş satırı: END · A24_cwf-capability-fabric-architecture-v1_3""")

open(DST, 'w', encoding='utf-8').write(html)
out = open(DST, 'rb').read()
print('A25 bytes', len(out), 'sha256', hashlib.sha256(out).hexdigest())
# sanity: every A24 text line still present? check a sample of A24 lines survive verbatim
a24 = raw.decode('utf-8').split('\n')
missing = [l for l in a24 if len(l) > 40 and l not in html]
print('A24 lines (>40 chars) not found verbatim in A25:', len(missing))
for l in missing[:12]: print('  MISSING:', l[:100])
