with b as (select $b$<!-- relay-audit: v1 kind=card -->
CARD-M1-MCP-ISERROR-PASSTHROUGH-S164-1-v2

LANE: AG-1 (in mail-wait)
fanout: personalized (one lane, one body)
FROM: Architect, S164, 2026-09-30T02:55Z
SUPERSEDES: CARD-M1-MCP-ISERROR-PASSTHROUGH-S164-1-v1 (never inserted to a lane). scout-2's SCOUT-STATUS-REVIEW-CARD-M1-S164-1 (bus 2026-09-30T02:35:50Z; full text 19106 bytes in S164/, sha256 f479c27c630362dd3fd3b3f8c7e9d0746444685266ec46f3547ef5f97eebd027) returned RED at base 6a3824c2b5efd1764be178d05ba647feec06927c with thirteen paste-ready deltas Δ1–Δ13; every one is applied below by number. Read that file — it is part of this card; its §1–§7 are the measured ground for every line here.
SEAL: EXEMPT with ack = that review row 1341d78b-9ae4-4e8c-91ca-0f4a6357a3b7 (practice 136: this version applies exactly the scout's named deltas). GATE NOTE (§12.2, carried): the first insert of this v2 was refused by relay_adversary_gate AG009 because the ack named the row by artifact instead of by id; corrected here, bytes otherwise unchanged.
```evidence:adversary
ADVERSARY: EXEMPT
ack: 1341d78b-9ae4-4e8c-91ca-0f4a6357a3b7
```
AUTHORITY: OWNER-APPROVAL-S163-MEMORY-PLAN-1 (Track 1, M1) · OWNER-APPROVAL-S164-PLAN-1 item 2 · constitution §2 (the channel's verdict beats the bytes; empty ≠ zero) · FULL-TRACE · OWNER-RULING-S153-NO-ARMES-HARDCODE-1.
QUEUE: PREPARE NOW on a branch; OPEN THE PR ONLY when `gh pr list --state open` is empty, read twice 60 s apart (TOUR-HONESTY re-cut, AG-4, is ahead of you). Cut the branch from the master that exists at that moment (`git ls-remote origin refs/heads/master` twice; print it); if master moved since you prepared, re-base by cherry-pick -n onto the new master, never merge/rebase in place.
NO CRON TASK. GRAFT: graft first (graft/api/cwf/_lib/turn/mcpClient.md, toolResultClass.md, stageTools.md, stageClarify.md; graft/.graph/wiring.json). SECURITY: never print, echo, printenv or cat any environment variable.

## WHY (scout-2 re-measured at 6a3824c2b5efd1764be178d05ba647feec06927c; quote from `git archive origin/master`, never the shared clone)
W1 · `executeMCPTool` (mcpClient.ts:272-276) returns `Promise<string>`; content extraction :333-338; attempt span output `{ok:true, ms, resultBytes}` :342; the four JSON-error returns :284, :298 (config) and :360, :368 (transport). `result.isError` is never read (two lenses, zero hits). Installed SDK 1.29.0: `CallToolResult.isError` is an optional boolean (types.d.ts:2602), but `client.callTool` returns a UNION with the 2024-10-07 compat shape (client/index.d.ts:512-515), so `result.isError` types as `unknown` — spell it `result.isError === true`, exactly as toolBehaviorRecord.ts:241 already does on the census path. The SDK does not throw on isError (client/index.js:490-519): a tool-level failure arrives as a RESULT. (Δ1)
W2 · The door exists: `ClassifyInput.transportError` (toolResultClass.ts:144-155), ORDER 1 at :169-174 → `unreadable:tool-reported`. ONE call site, stageTools.ts:1718-1723, never passes it; examScorers.ts:180 (exam path) neither. No existing path carries the raw verdict into stage 07 (tool span :2167 is derived from resultClass; attempt span :342 has ok/ms/bytes only; PersistRawEntry types.ts:163-168 has no verdict). D1 is not a duplicate mechanism (§12.6 answered).
W3 · Consequence chain: toolError :1724 → ledger :1739-1744 → telemetry payload.ok :1846-1851 → tool span :2148-2168 → recordToolSuccess :1779-1781 (returns early on failed, toolExperienceFlush.ts:82-87) → answerUnbackedDespiteFailures toolOutcomes.ts:315-317 → chip chatSurface.ts:207 / toolEvidence.ts:208 → artifact observation :1826. ALL FOLLOW the classification. One hop does NOT: examScorers.readResult :176-184 re-classifies persisted raw bytes (E1-a honesty metric) — named as follow-up CARD-M1B, not fenced here (Δ11).
W4 · Callers: one production function, `executeThroughBackendSlot` (stageTools.ts:302-324; calls at :309 and :320), itself called at :1639 and :1671 (repair). 25 test files mock `executeMCPTool: vi.fn(…)` (list in the scout's §3); spanIOCompleteness.test.ts:331 calls the real function; 15 further mcpClient mocks do not name it and are unaffected. (Δ2)

## DESIGN
D1 · mcpClient.ts: `export interface McpToolOutcome { readonly text: string; readonly isError: boolean }`; `executeMCPTool` returns `Promise<McpToolOutcome>` — ONE function, richer return (scout ruling §3: the sibling saves nothing and adds a dead wrapper). Inside the attempt: `const isError = result.isError === true;` text byte-identical to today's `output`. The four JSON-error returns (:284, :298, :360, :368) become `{ text: JSON.stringify({ error: … }), isError: true }`. The attempt span becomes `{ ok: true, isError, ms, resultBytes }` and its comment states: `ok` = the round-trip completed, `isError` = the tool's own verdict (Δ4, Δ7d — the pair is defined, not left to be misread). NAMED CONSEQUENCES (Δ4): a thrown transport failure is relabelled `unreadable:transport` → `unreadable:tool-reported` (classifier ORDER 1 wins before the regex; the regex at toolResultClass.ts:135 stays as a second lens); the config failures :284/:298, which classify `answered` today, become errors — a real gain.
D2 · stageTools.ts (Δ3): the four not-sent arms (misroute · policyDenial · cap · argRefusal, :1623-1635) stay TEXT. Only the sent arm yields an outcome: `const sentOutcome = callWasSent ? await executeThroughBackendSlot(…) : null; const resultTextRaw = sentOutcome?.text ?? <today's arm chain>;` repair (:1664-1676) keeps feeding `rawOutcome.text` to `repairGatewayArguments` (text-gated, toolCallRepair.ts:84-89) and yields `repairedOutcome` from the same call; `const outcome = repairedOutcome ?? sentOutcome; const resultText = outcome?.text ?? resultTextRaw;` at :1718: `classifyToolResult({ resultText, args, transportError: outcome?.isError === true })`. No isError value is manufactured for a call that was never sent. `executeThroughBackendSlot` returns `Promise<McpToolOutcome>`; brake logic byte-identical. COUNT SEMANTICS, stated (scout §5): first call isError + repaired OK ⇒ ledger calls +1, successes +1, failures +0, toolRepairs[k].count +1, ctx.toolCallCount +2; the first failure lives in the attempt span and the repair record only — unchanged from today. Correct the stale comment :1766-1771 (it describes toolError as a text sniff) (Δ13).
D3 · RULING ON THE SELF-CORRECTION TEXT (Δ5, Architect's decision): M1 must NOT silently widen S1's "the upstream sentence never travels" to every tool-reported error, because P6.7 (mcpClient.ts:302-306) relies on the model reading a deterministic validation error and self-correcting. RULED: the classification is a FAILURE (accounting, ledger, experience, chips, spans all read `unreadable:tool-reported`), AND the model-facing refusal carries the tool's own message as a quoted attribute: `modelFacingRefusal` (toolResultClass.ts:435-443) gains an optional `toolMessage: string` = `scrubbedAttrValue(text, 240)` when `reason === 'tool-reported'` only; the JSON shape stays `{toolCall:'unreadable', reason:'tool-reported', toolMessage:'…'}` so it can never be mistaken for data (it has no records field and keeps the S1 vocabulary), while "materialNumber must be 10 digits" still reaches the model. Recognised rejection sentences (schema-validation/auth/transport regex) keep today's behaviour: NO toolMessage. The lane updates the P6.7 comment to say exactly this. toolResultClass.ts is therefore in the fence for THIS change only.
D4 · Tests (Δ6, Δ7): every one of the 25 mocks returns `okOutcome(text)` / `errOutcome(text)` from the new helper api/cwf/_lib/testing/mcpOutcome.ts; the five `as never` casts at resultBudgetStageWiring.test.ts:131,231,244,259,298 are replaced by okOutcome(...). After the change `git grep -nE "executeMCPTool: vi.fn\(async \(\) => '" -- api` and `git grep -n "as never" -- api/cwf/__tests__/resultBudgetStageWiring.test.ts` both print zero hits for executeMCPTool mocks (mocks are untyped against the module — a string mock left behind compiles and then `resultText.length` throws at :2149). toolResultClassWiring.test.ts:125-130 is changed to `errOutcome('{"error":"Tool execution failed: ECONNREFUSED"}')` expecting `reason: 'tool-reported'`, PLUS a sibling case where the same sentence arrives as `okOutcome(...)` and still reads `transport` (regex = live second lens). spanIOCompleteness.test.ts:508-517 pins the attempt span → gains `isError`.
D5 · UI/UX (OWNER-RULING-S160): no new data or screen — a tool-reported error enters the EXISTING failure count and the existing outage chip; stated so the rule is answered.
D6 · NO-HARDCODE: `isError` is the protocol's field; no backend id, tool name or sentence literal enters non-test source; new tests do NOT copy the existing ctx builders with a backend id literal (toolResultClassWiring.test.ts:42,60) (Δ12).
D7 · stageClarify (scout H10): ask-discovery reads the closure's MODEL copy (stageClarify.ts:1856-1860) and parses entities (:1873-1884); today an isError + `{"rows":[]}` payload parses as zero records → a false "not found"; after M1 it is the refusal JSON → `could-not-run`. Desired direction; NAMED and tested (F6).

## ORDERS
1. Re-measure W1–W4 at your base by `git archive` (quote file:line). Any premise differs → slip the bytes, STOP.
2. Implement D1–D4, D7 exactly. Before/after: `git grep -n "executeMCPTool" -- api src shared scripts`; no string-typed consumer remains; the two zero-hit greps of D4 printed.
3. FENCE (first commit, complete; `npm run build` BEFORE committing; every regenerated file joins): api/cwf/_lib/turn/mcpClient.ts · api/cwf/_lib/turn/stageTools.ts (incl. the :1766-1771 comment) · api/cwf/_lib/turn/toolResultClass.ts (ONLY modelFacingRefusal's optional toolMessage, D3) · api/cwf/_lib/testing/mcpOutcome.ts (new) · the 25 mock test files (list each) · api/cwf/__tests__/spanIOCompleteness.test.ts · toolResultClassWiring.test.ts · the new tests (F1–F6) · your report docs/relay/M1-MCP-ISERROR-PASSTHROUGH-S164-1-AG1-report.md · gate-regenerated files (manifest via reseal, graft cards, baselines). NOT toolOutcomes.ts · NOT examScorers.ts (CARD-M1B) · NOT fixtureMcpServer.ts · NOT entityDiscoverySync.ts / gatewayEnumerate.ts (named follow-ups).
4. TESTS = F1–F6 below, each a named test; fixture backend or the stage-07 in-process harness; no backend id literal.
5. GATES, ALL: `npm run build` (five gates) · `npm run typecheck:api` · `npm run check:tenant-zero` · the backend-name gate (build.yml step 9 — read .github/workflows/build.yml and run every step 1–11 command that can run locally; list each with its exit code) · `node --import tsx scripts/relayAudit.ts docs/relay/M1-MCP-ISERROR-PASSTHROUGH-S164-1-AG1-report.md` · vitest over the touched suites (the 25 + spanIOCompleteness + toolResultClassWiring + new). Quote each result line. No 7–39 hex in prose anywhere in the report (CP-8): full 40-hex inside evidence fences or none.
6. ONE commit on `phase/m1-mcp-iserror-passthrough-s164-1` (`git commit -F <file>`); push; `git ls-remote` the ref. If the PR cannot open yet (QUEUE), slip PREPARED with the head and go back to mail-wait; the Architect issues NOTICE-OPEN-PR-M1-S164-1 when the queue clears.
7. PR title "AG-1: M1 — MCP isError passes through to classifyToolResult; transport verdict beats bytes; refusal carries the tool's message". auto-merge arms; do not merge (scout-1 lands).
8. CI by the FULL 40-hex head; zero read twice; named waits ≤ 12 × 2 min; quote each workflow's conclusion and the `[merge-guard] VERDICT` line; SKIPPED named.
9. SLIP-CARD-M1-MCP-ISERROR-PASSTHROUGH-S164-1 (bus + fallback S164/): branch, head, parent, mock-file count, each gate line, workflow conclusions, VERDICT, `read relay_inbox at <ISO>, box empty`. Back to `node scripts/mail-wait.mjs AG-1 --budget-min 480`.

## FALSIFIERS
F1 · stage-07 composition with executeMCPTool mocked as `errOutcome('{"rows":[]}')` → classification `unreadable:tool-reported`; toolError true; ledger failures +1, successes unchanged; tool span `isError: true`, `toolCallClass: 'unreadable'`; the tool_experience ACCUMULATOR has NO entry for (backend, tool) after the call (recordToolSuccess is called and returns at toolExperienceFlush.ts:87 — assert the accumulator, not the call); model copy = `{toolCall:'unreadable', reason:'tool-reported', toolMessage:'{"rows":[]}'}`, never bare payload bytes; outage chip names 1 failure. PLUS one REAL executeMCPTool call against createFixtureMcpServer naming a tool absent from its vocabulary (fixtureMcpServer.ts:72-73) → `{ text: 'unknown tool <name>', isError: true }`. No fixture change. (Δ8)
F2 · the SAME payload as `okOutcome` → `answered`; every downstream field byte-identical to master.
F3 · fixture server `close()`d before the call → connect fails through the retry loop → `{ text: '{"error":"Tool execution failed: …"}', isError: true }` → `unreadable:tool-reported`; and the sibling: the same sentence as `okOutcome` → `unreadable:transport` via the regex. (Δ9, Δ7)
F4 · every existing toolResultClass and wiring test green with the mock-shape change only; the two D4 greps print zero hits.
F5 · `git diff origin/master...HEAD -- ':!**/__tests__/**' ':!**/testing/**'` adds no backend id, tool name or sentence literal.
F6 · stageClarify ask-discovery through the registered closure with executeMCPTool mocked as `errOutcome('{"rows":[]}')` → attempt outcome `no-answer`/`could-not-run`, NOT `answered, []` (stageClarify.ts:1873-1884). (Δ10)

FOLLOW-UPS NAMED, NOT FENCED (Δ11): CARD-M1B — PersistRawEntry gains optional `isError` via recordToolCall (stageTools.ts:246) and examScorers.readResult passes `transportError: entry.isError` (pre-phase rows absent → today's behaviour), so the E1-a honesty metric follows M1. Off-turn callTool paths ignoring isError: entityDiscoverySync.ts:389, gatewayEnumerate.ts:143/:160.

FORBIDDEN: a second execute function; parsing result text to infer an error; manufacturing isError for a not-sent call; any toolResultClass.ts change beyond D3; touching toolOutcomes.ts, examScorers.ts, fixtureMcpServer.ts; a migration; a merge commit; opening the PR while another is open; cron; printing an environment value.

END · CARD-M1-MCP-ISERROR-PASSTHROUGH-S164-1-v2
$b$ as t)
insert into public.relay_inbox (direction, lane_addr, artifact_name, body)
select 'to_lane','AG-1','CARD-M1-MCP-ISERROR-PASSTHROUGH-S164-1-v2', b.t from b where md5(b.t)='93bb6344069a628541d2014bc65c7b9b' and encode(sha256(convert_to(b.t,'UTF8')),'hex')='f0493d70de41abfea53bf519c971d16a64c90cc1b4753b61b00e399df0c1dc3a'
returning id, artifact_name, created_at;
